_Ones = {
    1: 'one',
    2: 'two',
    3: 'three',
    4: 'four',
    5: 'five',
    6: 'six',
    7: 'seven',
    8: 'eight',
    9: 'nine',
    10: 'ten',
    11: 'eleven',
    12: 'twelve',
    13: 'thirteen',
    14: 'fourteen',
    15: 'fifteen',
    16: 'sixteen',
    17: 'seventeen',
    18: 'eighteen',
    19: 'nineteen',
    0: 'zero'
}

_Tens = {
    2: 'twenty',
    3: 'thirty',
    4: 'forty',
    5: 'fifty',
    6: 'sixty',
    7: 'seventy',
    8: 'eighty',
    9: 'ninety'
}

_placeholders = {
    0: ' ',
    4: 'thousand',
    7: 'million',
    10: 'billion',
    13: 'trillion',
    16: 'quadrillion',
    19: 'quintillion',
    22: 'hextillion',
    25: 'septillion',
    28: 'octillion',
    31: 'nonillion',
    34: 'decillion',
    37: 'undecillion',
    40: 'duodecillion',
    43: 'tredecillion',
    46: 'quattuordecillion',
    49: 'quindecillion',
    52: 'hexdecillion',
    55: 'septendecillion',
    58: 'octodecillion',
    61: 'novemdecillion',
    64: 'vigintillion',
    67: 'unvigintillion',
    70: 'duovigintillion',
    73: 'trevigintillion',
    76: 'quattourvigintillion',
    79: 'quinvigintillion',
    82: 'hexvigintillion',
    85: 'septenvigintillion',
    88: 'octovigintillion',
    91: 'novemvigintillion',
    94: 'trigintillion',
    97: 'untrigintillion',
    100: 'duotrigintillion',
    100: 'googol',
}

